apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  # selector provided via kustomize
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
# Headless service used to get IP addresses for keycloak pods
apiVersion: v1
kind: Service
metadata:
  name: headless-keycloak-service
spec:
  clusterIP: None
# selector provided via kustomize
