apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: keycloak
          image: europeana/keycloak
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 60