resources:
- ../../base
- nodeport.yaml

patchesStrategicMerge:
- deployment_patch.yaml

commonLabels:
  app: keycloak-test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -test
images:
- name: keycloak-europeana
  newTag: "2.0"
